import { setupWorker } from "msw/browser";

import { handlers } from "./handlers";

/**
 * The browser-side mock API, started from `main.tsx` in dev only.
 *
 * Its service worker (`public/mockServiceWorker.js`) is regenerated by
 * `npm run msw:init`. It is deliberately excluded from `vite build` — see
 * `publicDir` in `vite.config.ts` — because a development mock has no business
 * inside a released wheel.
 */
export const worker = setupWorker(...handlers);
